config/routes.rb
Rails.application.routes.draw do

  root "products#index"

  get "customer/SignUp", to: "customers#add_customer", as: "add_customer"

  get "about", to: "pages#about"
  get "contact", to: "pages#contact"
  get "login", to: "customers#login", as: "login"

  get "checkout", to: "checkout#index", as: "checkout"
  get "checkout/apply_tax", to: "checkout#determine_tax", as: "apply_tax"
  get "checkout/province/:id", to: "checkout#determine_tax", as: "determine_tax"


  get 'products/index'
  # get 'products/:id', to: "products#show", as: "product"
  post 'products/add_to_cart/:id', to: "products#add_to_cart", as: "add_to_cart"
  delete 'products/remove_from_cart/:id', to: "products#remove_from_cart", as: "remove_from_cart"
  delete 'products/decrement_from_cart/:id', to: "products#decrement_from_cart", as: "decrement_from_cart"
  get 'products/clear_cart', to: "products#clear_cart", as: "clear_cart"

  resources 'products', only: [:index, :show] do
    collection do
      get 'search_results'
    end
  end

  # get 'orders/index'
  # get 'orders/show'

  # get 'categories/index'
  # get 'categories/show'

  # get "customers/index"

  # get 'provinces/index'
  # get 'provinces/show'
  # get "/provinces/:id", to: "provinces#show"

  resources :customers
  resources :provinces
  resources :categories
  resources :orders

  # GET	      /photos	          photos#index	  display a list of all photos
  # POST	    /photos	          photos#create	  create a new photo
  # GET	      /photos/new	      photos#new	    return an HTML form for creating a new photo
  # GET	      /photos/:id	      photos#show	    display a specific photo
  # PATCH/PUT	/photos/:id	      photos#update	  update a specific photo
  # DELETE	  /photos/:id	      photos#destroy	delete a specific photo
  # GET	      /photos/:id/edit	photos#edit	    return an HTML form for editing a photo

  # photos_path           returns /photos
  # new_photo_path        returns /photos/new
  # edit_photo_path(:id)  returns /photos/:id/edit (edit_photo_path(10) returns /photos/10/edit)
  # photo_path(:id)       returns /photos/:id (photo_path(10) returns /photos/10)

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  # associations
  has_many :product_categories
  has_many :products, through: :product_categories

  # validations
  validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # associations
  belongs_to :province

  has_many :customer_orders
  has_many :orders, through: :customer_orders

  # has_many :products, through: :orders #????

  # validations
  validates :name, presence: true

end

app/models/customer_order.rb
class CustomerOrder < ApplicationRecord
  belongs_to :Customer
  belongs_to :Order
end

app/models/order.rb
class Order < ApplicationRecord
  # associations
  belongs_to :customer

  has_many :order_products
  has_many :products, through: :order_products

  has_many :customer_orders
  has_many :customers, through: :customer_orders

  # validations
  validates :status, presence: true

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :Order
  belongs_to :Product
end

app/models/page.rb
class Page < ApplicationRecord
  validates :name, presence: true
  validates :content, length: {maximum: 999999}
end

app/models/product.rb
class Product < ApplicationRecord
  # associations
  has_many :product_categories
  has_many :categories, through: :product_categories

  has_many :order_products
  has_many :orders, through: :order_products

  # validations
  validates :name, presence: true

  # required for active storage
  has_one_attached :image

  # required for active admin customization?
  accepts_nested_attributes_for :product_categories, allow_destroy: true

  # pagination
  paginates_per 8
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product   # product_id FK in Products table in the ProductCategories table
  belongs_to :category  # category_id FK in the ProductCategories table
end

app/models/province.rb
class Province < ApplicationRecord
  # associations
  has_many :customers

  # validations
  validates :name, presence: true
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  before_action :initialize_session
  before_action :load_cart_variable

  def index
  end

  def determine_tax
    @province = Province.find(params[:id].to_i)
    @taxes = {"GST" => @province.GST, "PST" => @province.PST, "HST" => @province.HST}
    @GST_due = (@province.GST)*(@cart_subtotal)/100.0
    @PST_due = (@province.PST)*(@cart_subtotal)/100.0
    @HST_due = (@province.HST)*(@cart_subtotal)/100.0
    @total_tax_amount = @GST_due + @PST_due + @HST_due
    @cart_grandtotal = (@cart_subtotal + @total_tax_amount)
  end

  private
  def initialize_session
    session[:visit_count] ||= 0
    # session[:cart] ||= []
    session[:cart] ||= Hash.new
  end

  def load_cart_variable
    @cart_contents = Product.find(session[:cart].keys)
    @cart_subtotal = 0

    session[:cart].each do |prod_id,qty|
      price = Product.find(prod_id.to_i).price
      @cart_subtotal += (price*qty)/100.0
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  @statuses = %w[pending, paid, shipped]
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.all
  end

  def show
    @page = Page.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/province_helper.rb
module ProvinceHelper
end

app/views/checkout/_shipping_info_form.html.erb
<div class="block">
  <h3 class="title is-6" >Shipping Information:</h3>

  <%= form_with url: "/#", method: :post do |form| %>

    <%= form.label :customer_name, "Name", style: "display: block"  %>
    <%= form.text_field :customer_name, :required => true %>

    <%= form.label :address, "Address", style: "display: block"  %>
    <%= form.text_field :address, :required => true %>

    <%= form.label :province, "Province", style: "display: block"  %>
    <%= form.select :province, options_from_collection_for_select(Province.all, 'id', 'code'), include_blank: "select province" , style: "display: block" %>

    <%= form.submit "Proceed to Confirmation" %>
  <% end %>
</div>

app/views/checkout/determine_tax.html.erb
<h3 class="title is-4">Checkout</h3>

<%# cart contents %>
<%= render "products/cart_contents"%>

<p>Select Province to apply tax:</p>
 <nav class="navbar">
  <% Province.all.each do |p| %>
    <%= link_to p.name, determine_tax_path(p.id), :class=>"navbar-item" %>
  <% end %>
 </nav>

<br>
<div class="block">
  <p>Tax for <%= @province.name %> applied.</p>

  <% unless @province.GST == 0 %>
    <p>GST: <%= number_to_currency @GST_due %></p>
  <% end %>
    <% unless @province.PST == 0 %>
    <p>PST: <%= number_to_currency @PST_due %></p>
  <% end %>
    <% unless @province.HST == 0 %>
    <p>HST: <%= number_to_currency @HST_due %></p>
  <% end %>

  <p><strong class="title is-6">Grand Total:</strong> <%= number_to_currency @cart_grandtotal %></p>

</div>

<div class="block">
  <p>Already have an account? <%= link_to "Log In", login_path %></p>
  <p><%= link_to "Sign Up", new_customer_path %> to save your shipping information.</p>
</div>

<%# shipping information %>
<%= render "shipping_info_form" %>

app/views/checkout/index.html.erb
<h3 class="title is-4">Checkout</h3>

<%# cart contents %>
<%= render "products/cart_contents"%>

<div class="block">
  <p>Select Province to apply tax:</p>
   <nav class="navbar">
    <% Province.all.each do |p| %>
      <%= link_to p.name, determine_tax_path(p.id), :class=>"navbar-item" %>
    <% end %>
   </nav>
</div>