config/routes.rb
Rails.application.routes.draw do

  root "products#index"

  get "customer/SignUp", to: "customers#add_customer", as: "add_customer"

  get "about", to: "pages#about"
  get "contact", to: "pages#contact"
  get "login", to: "customers#login", as: "login"

  get "checkout", to: "checkout#index", as: "checkout"
  get "checkout/apply_tax", to: "checkout#determine_tax", as: "apply_tax"
  get "checkout/province/:id", to: "checkout#determine_tax", as: "determine_tax"


  get 'products/index'
  # get 'products/:id', to: "products#show", as: "product"
  post 'products/add_to_cart/:id', to: "products#add_to_cart", as: "add_to_cart"
  delete 'products/remove_from_cart/:id', to: "products#remove_from_cart", as: "remove_from_cart"
  delete 'products/decrement_from_cart/:id', to: "products#decrement_from_cart", as: "decrement_from_cart"
  get 'products/clear_cart', to: "products#clear_cart", as: "clear_cart"

  resources 'products', only: [:index, :show] do
    collection do
      get 'search_results'
    end
  end

  # get 'orders/index'
  # get 'orders/show'

  # get 'categories/index'
  # get 'categories/show'

  # get "customers/index"

  # get 'provinces/index'
  # get 'provinces/show'
  # get "/provinces/:id", to: "provinces#show"

  resources :customers
  resources :provinces
  resources :categories
  resources :orders

  # GET	      /photos	          photos#index	  display a list of all photos
  # POST	    /photos	          photos#create	  create a new photo
  # GET	      /photos/new	      photos#new	    return an HTML form for creating a new photo
  # GET	      /photos/:id	      photos#show	    display a specific photo
  # PATCH/PUT	/photos/:id	      photos#update	  update a specific photo
  # DELETE	  /photos/:id	      photos#destroy	delete a specific photo
  # GET	      /photos/:id/edit	photos#edit	    return an HTML form for editing a photo

  # photos_path           returns /photos
  # new_photo_path        returns /photos/new
  # edit_photo_path(:id)  returns /photos/:id/edit (edit_photo_path(10) returns /photos/10/edit)
  # photo_path(:id)       returns /photos/:id (photo_path(10) returns /photos/10)

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/product.rb
class Product < ApplicationRecord
  # associations
  has_many :product_categories
  has_many :categories, through: :product_categories

  has_many :order_products
  has_many :orders, through: :order_products

  # validations
  validates :name, presence: true

  # required for active storage
  has_one_attached :image

  # required for active admin customization?
  accepts_nested_attributes_for :product_categories, allow_destroy: true

  # pagination
  paginates_per 8
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # before any controller actions are performed, run the following (private) functions
  before_action :initialize_session #create empty cart array, or visit count set to 0, if not already initialized
  before_action :increment_visit_count, only: [:index, :about]
  before_action :load_cart_variable

  def index
    @products = Product.all.page(params[:page])
  end

  def show
    @product = Product.find(params[:id])
  end

  def search_results

    if params[:commit] == "Filter"
      @products = Product.joins(:categories).where(categories: {id: params[:category].to_i}).distinct
    end

    unless params[:filter].blank?
      days = 60
      if params[:filter] == "new"
        @filter_heading = "New Products!"
        @filter_tagline = "Products posted in the last #{days} days."
        @products = Product.where("created_at > ?", Time.now - days.day)
      elsif params[:filter] == "sale"
        @filter_heading = "On Sale!"
        @filter_tagline = "Products whose price has been reduced in the last #{days} days."
        @products = Product.where("created_at > ?", Time.now - days.day)
      elsif params[:filter] == "recent"
        days = 5
        @filter_heading = "Recently Updated!"
        @filter_tagline = "Products that have been updated in the last #{days} days."
        @products = Product.where("updated_at > ?", Time.now - days.day)
      end
    end

    if params[:commit] == "Search"
      # search without category filter
      if params[:category].empty?
        @products = Product.where("name LIKE ?", "%#{params[:query]}%")

      # search with category filter
      else
        @products = Product.joins(:categories).distinct
        # @products = Product.where("name LIKE ?", "%#{params[:query]}%").joins(:categories).where(category: {id: params[:category]}.to_i).distinct
      end
    end

  end

  def filter_by_category
    # retrieve from the product_categories join table
    # select product_id from product_categories where category_id is X
    # product.id = product_category= product_id

    @products = Product.joins(:categories).where(categories: {id: params[:category]}).distinct
    # Product.join(:product_categories)
    # SELECT * FROM products JOIN product_categories ON product.id = product_categories.product_id

    # Book.joins(:reviews)
    # SELECT * FROM books JOIN reviews ON reviews.book_id = books.id
  end

  def add_to_cart
    prod_key = params[:id] # is of datatype string
    # add the product id parameter to the end of the cart array stored in the sessions hash with a key of cart
    # add the id to cart, unless it is already there
    # session[:cart] << params[:id].to_i unless session[:cart].include?(params[:id].to_i)
    if session[:cart].keys.include?(prod_key)
      # if session[:cart].has_key?(prod_key)
          # product is already in the cart, increment
        session[:cart][prod_key] += 1
      else
        # product is not in the cart
        session[:cart][prod_key] = 1
      end

    # prevent rails from trying to load up a view of the same name as the action
    redirect_to products_index_path
  end

  def remove_from_cart
    prod_key = params[:id]
    session[:cart].delete(prod_key)

    redirect_to products_index_path
  end

  def decrement_from_cart
    prod_key = params[:id]
    if session[:cart][prod_key] == 1
      session[:cart].delete(prod_key)
    else
      session[:cart][prod_key] -= 1
    end

    redirect_to products_index_path
  end

  def clear_cart
    session[:cart] = Hash.new
    redirect_to products_index_path
  end

  def determine_tax
    @taxes = Tax.where(id: params[].to_i)
  end

  private
  def initialize_session
    session[:visit_count] ||= 0
    # session[:cart] ||= []
    session[:cart] ||= Hash.new
  end

  def load_cart_variable
    # loads a set of objects from the db
    # @cart_contents = Product.find(session[:cart])
    @cart_contents = Product.find(session[:cart].keys)
    # @cart_contents = Product.find(session[:cart][:prod_key])
    @cart_subtotal = 0
    session[:cart].each do |prod_id,qty|
      price = Product.find(prod_id.to_i).price
      @cart_subtotal += (price*qty)/100.0
    end
  end

  def increment_visit_count
    session[:visit_count] += 1
    @visit_count = session[:visit_count]
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_cart_contents.html.erb
<%# display cart contents %>
<div class="block">
  <% if @cart_contents.empty?%>
    <p>No items in cart.</p>
  <% else %>
    <h3 class="title is-6">Shopping Cart:</h3>
    <table class="table is-striped">
      <tr>
        <th></th>
        <th>Item</th>
        <th>QTY</th>
        <th>Unit Price</th>
      </tr>
      <% @cart_contents.each do |p|%>
        <tr>
          <td>
            <% if p.image.present? %>
              <%= image_tag p.image.variant(resize_to_fit: [50,50]) %>
            <% end %>
          </td>
          <td>
            <%= p.name %>
          </td>
          <td>
            <%= button_to "+", add_to_cart_path(p.id), method: :post %>
            <%= session[:cart][p.id.to_s]  %>
            <%= button_to "-", decrement_from_cart_path(p.id), method: :delete %>
          </td>
          <td>
            <%= number_to_currency p.price.to_i/100.0  %>
          </td>
          <td>
            <%= button_to "x", remove_from_cart_path(p.id), method: :delete %>
          </td>
        </tr>
      <% end %>
  </table>
  <p><strong class="title is-6">Subtotal:</strong> <%= number_to_currency @cart_subtotal %></p>
  <% end %>
</div>

<%# debugging %>
<div class="block">
  <%# <%=debug session[:visit_count]%>

  <%# <h3>Debug session[:cart]</h3> %>
  <%# debug session[:cart]%>

  <%# <h3>Debug params</h3> %>
  <%# params %>
</div>

app/views/products/_filterform.erb
<%= form_with url: search_results_products_path, method: :get do |form| %>
  <%= form.select :category, [options_from_collection_for_select(Category.all, 'id', 'name'),"onsale"] %>
  <%= form.submit "Filter" %>
<% end %>

<%# <nav class="navbar"> %>
  <%# Category.all.each do |c| %>
    <%# link_to c.name, "filter_products_path/#{c.id}", :class=>"navbar-item" %>
  <%# end %>
<%# </nav> %>

<nav class="navbar">
  <%= link_to "New!", "/products/search_results?filter=new", :class=>"navbar-item" %>
  <%= link_to "On Sale!", "/products/search_results?filter=sale", :class=>"navbar-item" %>
  <%= link_to "Recently Updated!","/products/search_results?filter=recent", :class=>"navbar-item" %>
</nav>

app/views/products/_product.html.erb
<% if show_page %>
  <div class="column is-3 is-flex-direction-row">
<% else %>
  <div class="column is-3 is-flex-direction-row">
<% end %>

    <div class="card">
        <%# product details %>

        <div class="card-image">
          <% if product.image.present? %>
              <%= image_tag product.image.variant(resize_to_fit: [275,275]) %>
          <% end %>
        </div>

        <div class="card-content">
          <%# card title %>
          <% if show_page %>
            <h3 class="title is-6"><%= product.name %></h3>
          <% else %>
            <h3 class="title is-6"><%= link_to product.name, product %></h3>
          <% end %>

          <%# card tags %>
          <% product.categories.each do |c| %>
            <span class="tag is-link is-light is-rounded"><%= c.name %></span>
          <% end %>
          <br>

          <%# product description %>
          <p><%= product.description %></p>
          <p>price: <%= number_to_currency product.price.to_i/100.0 %></p>
        </div>

        <div class="card-content">
          <%# buttons %>
          <% if @cart_contents.include?(product) %>
            <%= button_to "+", add_to_cart_path(product.id), method: :post %>
            <p>QTY: <%= session[:cart][product.id.to_s] %> </p>
            <%= button_to "-", decrement_from_cart_path(product.id), method: :delete %>
            <p><%= button_to "remove from cart", remove_from_cart_path(product.id), method: :delete %></p>
          <% else %>
            <p><%= button_to "add to cart", add_to_cart_path(product.id), method: :post %></p>
          <% end %>
        </div>

    </div>  <%# end card div %>

  </div>  <%# end column div %>

<% if show_page %>
  <p><%= link_to "back", products_path %></p>
<% end %>

app/views/products/_searchform.html.erb
<%= form_with url: search_results_products_path, method: :get do |form| %>
  <%= form.text_field :query, :required => true %>
  <%# form.select :category, ["Fiction", "Non-Fiction"] %>
  <%= form.select :category, options_from_collection_for_select(Category.all, 'id', 'name'), include_blank: true %>
  <%= form.submit "Search" %>
<% end %>

app/views/products/index.html.erb
<h1 class="title is-3">Products Collection</h1>

<%# category filter %>
<div class="block">
  <p>Filter products by category:</p>
  <%= render "filterform" %>
</div>

<%# search form %>
<div class="block">
  <p>Search products:</p>
  <%= render "searchform" %>
</div>

<%# display cart contents %>
<%= render "cart_contents"%>

<div class="block">
  <% unless @cart_contents.empty?%>
    <p><%= link_to "Checkout", checkout_path %></p>
    <p><%# button_to "Checkout", checkout_path, method: :post %></p>
    <%# button_to "Clear Cart", clear_cart_path, method: :delete %>
    <%# button_to "Clear Cart", clear_cart_path, method: :post %>
    <p><%= link_to "Clear Cart", clear_cart_path %></p>
  <% end %>
</div>

<div class="columns is-multiline">
  <%# render @products %>
  <%= render partial: 'product',
              collection: @products,
              locals: {show_page: false} %>
</div>

<nav class="pagination is-rounded">
  <ul class="pagination-list">
    <%= paginate @products, :class => "title is-4 pagination-link "%>
  </ul>
</nav>

app/views/products/search_results.html.erb
<h1 class="title is-4">Search Results</h1>

<%# params %>

<div class="block">
  <%# invalid search %>
  <% if params[:query].blank? && params[:category].blank? && params[:filter].blank? %>
    <p>Please try a valid search.</p>

  <%# filter by category %>
  <% elsif params[:commit] == "Filter"%>
      <p>Displaying <span class="tag is-link is-light is-rounded"><%= Category.find(params[:category].to_i).name %></span> products.</p>

  <%# keyword search %>
  <% elsif params[:commit] == "Search"%>
    <p>You searched for '<%= params[:query] %>'.</p>
      <% unless params[:category].blank? %>
        <p>Search filtered by category: <span class="tag is-link is-light is-rounded"><%= Category.find(params[:category].to_i).name %></span></p>
      <% end %>

  <%# new/sale/updated filter %>
  <% elsif params[:filter].blank? == false %>
    <p class="title is-5"><%= @filter_heading %></p>
    <p class="title is-6"><%= @filter_tagline %></p>
  <% end %>

  <% if @products.nil? || @products.empty? %>
    <p>No products found.</p>
  <% else %>
    <p><%= pluralize(@products.size, "result")%> found.</p>

    <%= link_to "Back", products_index_path %>

    <div class="columns is-multiline">
      <%# render @products %>
      <%= render partial: 'product',
                  collection: @products,
                  locals: {show_page: false} %>
    </div>
  <% end %>

  <%= link_to "Back", products_index_path %>
</div>

app/views/products/show.html.erb
<h1 class="title is-3">Product Member</h1>
<%# render @product %>
<%= render partial: 'product',
            object: @product,
            locals: {show_page: true} %>