config/routes.rb
Rails.application.routes.draw do

  root "products#index"

  get "customer/SignUp", to: "customers#add_customer", as: "add_customer"

  get "about", to: "pages#about"
  get "contact", to: "pages#contact"
  get "login", to: "customers#login", as: "login"

  get "checkout", to: "checkout#index", as: "checkout"
  get "checkout/apply_tax", to: "checkout#determine_tax", as: "apply_tax"
  get "checkout/province/:id", to: "checkout#determine_tax", as: "determine_tax"


  get 'products/index'
  # get 'products/:id', to: "products#show", as: "product"
  post 'products/add_to_cart/:id', to: "products#add_to_cart", as: "add_to_cart"
  delete 'products/remove_from_cart/:id', to: "products#remove_from_cart", as: "remove_from_cart"
  delete 'products/decrement_from_cart/:id', to: "products#decrement_from_cart", as: "decrement_from_cart"
  get 'products/clear_cart', to: "products#clear_cart", as: "clear_cart"

  resources 'products', only: [:index, :show] do
    collection do
      get 'search_results'
    end
  end

  # get 'orders/index'
  # get 'orders/show'

  # get 'categories/index'
  # get 'categories/show'

  # get "customers/index"

  # get 'provinces/index'
  # get 'provinces/show'
  # get "/provinces/:id", to: "provinces#show"

  resources :customers
  resources :provinces
  resources :categories
  resources :orders

  # GET	      /photos	          photos#index	  display a list of all photos
  # POST	    /photos	          photos#create	  create a new photo
  # GET	      /photos/new	      photos#new	    return an HTML form for creating a new photo
  # GET	      /photos/:id	      photos#show	    display a specific photo
  # PATCH/PUT	/photos/:id	      photos#update	  update a specific photo
  # DELETE	  /photos/:id	      photos#destroy	delete a specific photo
  # GET	      /photos/:id/edit	photos#edit	    return an HTML form for editing a photo

  # photos_path           returns /photos
  # new_photo_path        returns /photos/new
  # edit_photo_path(:id)  returns /photos/:id/edit (edit_photo_path(10) returns /photos/10/edit)
  # photo_path(:id)       returns /photos/:id (photo_path(10) returns /photos/10)

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  # associations
  has_many :product_categories
  has_many :products, through: :product_categories

  # validations
  validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # associations
  belongs_to :province

  has_many :customer_orders
  has_many :orders, through: :customer_orders

  # has_many :products, through: :orders #????

  # validations
  validates :name, presence: true

end

app/models/customer_order.rb
class CustomerOrder < ApplicationRecord
  belongs_to :Customer
  belongs_to :Order
end

app/models/order.rb
class Order < ApplicationRecord
  # associations
  belongs_to :customer

  has_many :order_products
  has_many :products, through: :order_products

  has_many :customer_orders
  has_many :customers, through: :customer_orders

  # validations
  validates :status, presence: true

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :Order
  belongs_to :Product
end

app/models/page.rb
class Page < ApplicationRecord
  validates :name, presence: true
  validates :content, length: {maximum: 999999}
end

app/models/product.rb
class Product < ApplicationRecord
  # associations
  has_many :product_categories
  has_many :categories, through: :product_categories

  has_many :order_products
  has_many :orders, through: :order_products

  # validations
  validates :name, presence: true

  # required for active storage
  has_one_attached :image

  # required for active admin customization?
  accepts_nested_attributes_for :product_categories, allow_destroy: true

  # pagination
  paginates_per 8
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product   # product_id FK in Products table in the ProductCategories table
  belongs_to :category  # category_id FK in the ProductCategories table
end

app/models/province.rb
class Province < ApplicationRecord
  # associations
  has_many :customers

  # validations
  validates :name, presence: true
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.all
  end

  def show
    @page = Page.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/province_helper.rb
module ProvinceHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="columns is-centered">
            <div class="column is-3"></div>
            <p class="column has-text-centered">850 8th St</p>
            <p class="column has-text-centered is-2">Canmore, Alberta</p>
            <p class="column has-text-centered">T2W 5B4</p>
            <p class="column has-text-centered">CANADA</p>
            <div class="column is-3"></div>
    </div>
    <div class="columns is-centered">
        <div class="column is-2"></div>
        <p class="column has-text-centered is-4">Website Design & Development</p>
        <p class="column has-text-centered is-1">&bull;</p>
        <p class="column has-text-centered is-2">Marissa Steindel</p>
        <p class="column has-text-centered">&bull;</p>
        <p class="column has-text-centered is-1">2022</p>
        <div class="column has-text-centered is-2"></div>
    </div>
</footer>

app/views/layouts/_menu.html.erb
<div id="hero">
    <p>crust <span>&</span> crumb</p>
</div>

<nav class="navbar is-primary">
  <%= link_to "Home", root_path, :class=>"navbar-item" %>
  <%= link_to "About", about_path, :class=>"navbar-item" %>
  <%= link_to "Contact Us", contact_path, :class=>"navbar-item" %>
  <%= link_to "Admin", admin_root_path, :class=>"navbar-item" %>
  <% if session[:cart].present? %>
    <%= link_to "Checkout[#{session[:cart].size}]", checkout_path, :class=>"navbar-item" %>
  <% end %>
  <%= link_to "Login", login_path, :class=>"navbar-item" %>
  <%= link_to "Create Account", new_customer_path, :class=>"navbar-item" %>
</nav>
<nav class="navbar is-warning">
    <%= link_to "Products Collection", products_path, :class=>"navbar-item" %>
    <%= link_to "Categories Collection", categories_path, :class=>"navbar-item" %>
    <%= link_to "Provinces Collection", provinces_path, :class=>"navbar-item" %>
    <%= link_to "Customers Collection", customers_path, :class=>"navbar-item" %>
    <%= link_to "Orders Collection", orders_path, :class=>"navbar-item" %>
</nav>

  <nav class="breadcrumb" aria-label="breadcrumbs">
    <ul class="navbar-item">
      <li><%= link_to params[:controller].capitalize, "#{params[:controller]}" %> </li>
      <li><%= link_to params[:action].capitalize, "#{params[:controller]}##{params[:action]}" %> </li>
      <% unless params[:id].nil? %>
        <li><%= link_to params[:id].capitalize, "#{params[:controller]}##{params[:action]}/#{params[:id]}" %> </li>
      <% end %>
    </ul>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BakeryEcommerce</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  </head>

  <body>
    <%= render "layouts/menu"%>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "layouts/footer"%>
  </body>
</html>

app/views/pages/_page.html.erb
<h1> <%= page.name %> </h1>

app/views/pages/about.html.erb
<h1 class="title is-2">About Us</h1>

<div class="columns">
    <div class="column is-8 is-centered">
      <p> <%= Page.where(:name => "About").first.content %> </p>
      <%# <p>Nestled in the southwest corner of charming Canmore, crust & crumb offers a wide selectionfresh daily breads and pastries. The bakerysourdough leavened loaves and a variety of weeklchoice specials. crust & crumb partners wproducers to source the freshest and highest qualigrains, eggs, fruit preserves, and veggies. </p> %>
    </div>
</div>

<div id="picbanner">
    <%= image_tag "pexels-life-of-pix-9095.jpg" %>
    <%= image_tag "jonathan-pielmayer-j1gr2w10EtQ-unsplash.jpg" %>
    <%= image_tag "brands-people-yHjcZCaiKFY-unsplash.jpg" %>
    <%= image_tag "bermix-studio-8tQ7rBFgPu8-unsplash.jpg" %>
    <%= image_tag "mae-mu-Emhz3miT6mo-unsplash.jpg" %>
</div>

    <div class="columns is-8 is-centered">
        <div class="content column">
            <h4 class="title is-5">mainstay loaves</h4>
            <ul>
                <li>rustic sourdough</li>
                <li>flax & pepitas</li>
                <li>jalepe&ntilde;o cheddar</li>
                <li>cracked rye</li>
                <li>multigrain</li>
            </ul>
        </div>

        <div class="content column">
            <h4 class="title is-5">weekly specials</h4>
            <ul>
                <li>loaf</li>
                <li>cookie</li>
                <!-- <li>loaf</li> -->
                <li>hand pie</li>
                <li>gallette</li>
                <li>baker's choice</li>
            </ul>
        </div>
    </div>

app/views/pages/contact.html.erb
<h1 class="title is-2">Contact Us</h1>

<form id="contactForm" action="index.html" method="post">
<div id="preorder">
    <%# <p>Interested in a pre-order or have a catering inquiry?</p>
    <p>Give us a shout! We love to hear your feedback.</p> %>
    <p> <%= Page.where(:name => "Contact").first.content %> </p>
</div>
<div id="contactInfo">

    <ul>
        <li>
            <label for="fullname">Full Name</label>
            <input id="fullname" name="fullname" type="text" />
            <%# <p class="contactError error" id="fullname_error">* Required field</p> %>
        </li>

        <li>
            <label for="phone">Phone Number</label>
            <input id="phone" name="phone" type="text" placeholder="    _ _ _  - _ _ _ - _ _ _ _" />
            <%# <p class="contactError error" id="phone_error">* Required field</p> %>
            <%# <p class="contactError error" id="phone_format_error">* Invalid phone number</p> %>
        </li>

        <li>
            <label for="email">Email</label>
            <input id="email" name="email" type="text" />
            <%# <p class="contactError error" id="email_error">* Required field</p> %>
            <%# <p class="contactError error" id="email_format_error">* Invalid email address</p> %>
        </li>
        <li>
            <label for="comments">Comments</label><br />
            <textarea id="comments" name="comments" rows="8" cols="50" ></textarea>
            <%# <p class="contactError error" id="comments_error">* Required field</p> %>
        </li>
        <!-- <li> * focus should include a change in background and font color</li> -->
    </ul>
</div>

    <div class="buttons">
        <button type="submit" id="submit">submit</button>
        <button type="reset" id="clear">clear</button>
    </div>
</form>

app/views/pages/index.html.erb
<h1>Pages Collection</h1>
<%= render @pages %>

app/views/pages/show.html.erb
<h1>Page Member</h1>
<%= render @page %>